# Generated by Django 2.1.1 on 2018-10-18 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='name',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
