# Generated by Django 2.1.1 on 2018-10-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_download'),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='resource',
            name='technicalFieldId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.TechnicalField'),
        ),
    ]
