# Generated by Django 2.1.1 on 2018-10-28 09:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0003_auto_20181027_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwoTechnicalField',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('technicalFieldId', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.TechnicalField')),
            ],
        ),
        migrations.RemoveField(
            model_name='resource',
            name='technicalFieldId',
        ),
        migrations.AddField(
            model_name='resource',
            name='twoTechnicalFieldId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='file.TwoTechnicalField'),
        ),
    ]
