# Generated by Django 2.1.1 on 2018-10-13 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0002_auto_20181013_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_type_two',
            old_name='two_id',
            new_name='one_id',
        ),
    ]
