# Generated by Django 2.1.1 on 2018-10-13 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0003_auto_20181013_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_type_three',
            name='two_id',
        ),
    ]
