# Generated by Django 2.1.1 on 2018-10-13 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0004_remove_product_type_three_two_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_type_three',
            name='product_type',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='product_type_two',
            name='product_type',
            field=models.CharField(max_length=11),
        ),
    ]
