# Generated by Django 2.1.1 on 2018-10-14 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0006_product_type_three_two_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('price', models.FloatField(default=0.0)),
                ('category', models.IntegerField(default=0)),
                ('pnum', models.IntegerField(default=0)),
                ('imgurl', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=100)),
                ('upload_time', models.DateTimeField(null=True)),
            ],
        ),
    ]
