# Generated by Django 2.1.1 on 2018-10-15 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0009_products_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_collect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_resource', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resource.Products')),
            ],
        ),
    ]
