# Generated by Django 2.1.1 on 2018-10-15 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181013_1124'),
        ('resource', '0010_user_collect'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_collect',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Info'),
        ),
    ]
