# Generated by Django 2.1.1 on 2018-10-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0011_user_collect_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='upload_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
