# Generated by Django 2.1.1 on 2018-10-15 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0013_auto_20181015_0958'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_collect',
            name='collect_resource',
        ),
    ]
