# Generated by Django 2.1.1 on 2018-10-15 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0014_remove_user_collect_collect_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_collect',
            name='collect_resource',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resource.Products'),
        ),
    ]
