# Generated by Django 2.1.1 on 2018-10-15 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20181013_1124'),
        ('resource', '0015_user_collect_collect_resource'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='user_collect',
            unique_together={('user', 'collect_resource')},
        ),
    ]
