# Generated by Django 2.1.1 on 2018-10-18 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_address'),
        ('resource', '0016_auto_20181015_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unitPrice', models.DecimalField(decimal_places=2, max_digits=11)),
                ('ordertime', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_good', to='user.Info')),
                ('buyerAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_address', to='user.Address')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_good', to='user.Info')),
                ('sellerAddress', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller_address', to='user.Address')),
            ],
        ),
    ]
