# Generated by Django 2.1.1 on 2018-10-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0017_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sellernum',
            field=models.IntegerField(default=1),
        ),
    ]
