# Generated by Django 2.1.1 on 2018-10-18 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0018_order_sellernum'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='buyernum',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
