# Generated by Django 2.1.1 on 2018-10-20 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0019_auto_20181018_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='good',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='resource.Products'),
        ),
    ]
