# Generated by Django 2.1.1 on 2018-10-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0020_order_good'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guaranty', models.IntegerField(default=0)),
                ('statusName', models.CharField(max_length=20)),
            ],
        ),
    ]
