# Generated by Django 2.1.1 on 2018-10-23 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0021_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='imgurl',
            field=models.CharField(max_length=256),
        ),
    ]
