# Generated by Django 2.1.1 on 2018-10-23 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resource', '0022_auto_20181023_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
