# Generated by Django 2.1.1 on 2018-10-13 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=40)),
                ('sex', models.BooleanField(max_length=2)),
                ('level', models.IntegerField()),
                ('email', models.CharField(max_length=40)),
                ('icon', models.CharField(max_length=80)),
                ('one', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('province_name', models.CharField(max_length=10)),
                ('p_c', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.City')),
            ],
        ),
    ]
