# Generated by Django 2.1.1 on 2018-10-13 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_city_info_province'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='province',
            name='p_c',
        ),
        migrations.AddField(
            model_name='city',
            name='c_p',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.Province'),
        ),
    ]
