# Generated by Django 2.1.1 on 2018-10-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20181013_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='icon',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='info',
            name='one',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='sex',
            field=models.BooleanField(default=0, max_length=2),
        ),
    ]
