# Generated by Django 2.1.1 on 2018-10-13 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_u_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='u_info',
        ),
    ]
