# Generated by Django 2.1.1 on 2018-10-22 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_info_integral'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='concact_name',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='concact_telephone',
            field=models.CharField(max_length=11, null=True),
        ),
    ]
