# Generated by Django 2.1.1 on 2018-10-23 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181022_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='default',
            field=models.IntegerField(default=0),
        ),
    ]
