# Generated by Django 2.1.1 on 2018-10-29 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_address_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='detailed_address',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
