# Generated by Django 2.1.1 on 2018-10-29 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_address_detailed_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='detailed_address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
